version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  service_a:
    build: ./service_a
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
  service_b:
    build: ./service_b
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
  worker:
    build: ./worker
    depends_on:
      - rabbitmq
